### ISSUE TITLE
Indels aren't calculated correctly

### ISSUE THREAD

**Issue by MichaelRade** [biocore/deblur#178] opened 2018-08-03 18:30 UTC
Hi,
Indels aren't calculated correctly because `sub_seq_i` and `sub_seq_j` are identical.

deblurring.py
160 `sub_seq_i = seq_i.np_sequence[:length]`
161 `sub_seq_j = seq_i.np_sequence[:length]`

**Comment by amnona** [comment] 2018-08-04 08:39
Hi,
thanks for the feeback.
I didn't fully understand what you mean regarding the indel calculation problem.
can you please elaborate what exactly you think the problem is?
can you give an example where you think the indel calculation isn't correct (starting from the non-aligned sequences)?

thanks
Amnon

**Comment by MichaelRade** [comment] 2018-08-04 10:53
Hi,
for example:
`seq_i.sequence = ---GGAGGGT-----`
`seq_j.sequence = ---AGG-GCGG----`
`seq_i.np_sequence = [4 4 4 2 2 0 2 2 2 3 4 4 4 4 4]`
`seq_j.np_sequence = [4 4 4 0 2 2 4 2 1 2 2 4 4 4 4]`

In line 160/161 you say this:
`sub_seq_i = seq_i.np_sequence[:length]`
`sub_seq_j = seq_i.np_sequence[:length]`
 "sub_seq_i" and "sub_seq_j" assigned the same sequence. So "sub_seq_i == sub_seq_j"
Therefore:
`sub_seq_i  = [4 4 4 2 2 0 2 2 2 3 4 4 4 4 4]`
`sub_seq_j =  [4 4 4 2 2 0 2 2 2 3 4 4 4 4 4]`

in line 163 you say
`mask = (sub_seq_i != sub_seq_j)`
Because "sub_seq_i " and "sub_seq_j " are always equal all element in "mask" have the boolean false.

Consequently in line 165 "mut_is_indel " will be always an empty list
`mut_is_indel = np.logical_or(sub_seq_i[mask] == 4, sub_seq_j[mask] == 4)`

If you replace in line 161 **sub_seq_j = seq_i.np_sequence[:length]** with **sub_seq_j = seq_j.np_sequence[:length]** i think it will be work.

**Comment by MichaelRade** [comment] 2018-08-04 11:55
Hi,
thanks. II'm going to check this out. Regarding your question: I've decided to read the scripts if I want to use it for my analyses. Let's see how long I can keep that up :)

**Comment by wasade** [comment] 2018-08-04 18:29
Thank you @MichaelRade for reporting, and for a detailed example of the bug. I'm reopening the issue until a fix is in place.

**Comment by RNAer** [comment] 2018-09-12 17:32
fix thru #179

**Closed by RNAer** 2018-09-12 17:32 UTC
